url: "http://typeharder.com"

permalink: /:categories/:year/:month/:day/:title/

title: Type Harder!
description: A site by Sean Kleinjung, software tinkerer.
google_analytics: UA-135667639-3

markdown: kramdown