url: "http://librarymeetsworld.com"

permalink: /:categories/:year/:month/:day/:title/

title: Library Meets World
description: A site by JK, badass librarian out to change the world for the better through librarianship.


markdown: kramdown
